<?php
/**
 * Permalink Handler - Redirects News category posts to source URLs
 */

if ( ! defined( 'WPINC' ) ) {
    die;
}

class WP_RSS_Importer_Permalink_Handler {

    /**
     * Filter post permalink to return source URL for feed items
     *
     * @param string $permalink The post's permalink
     * @param WP_Post $post The post object
     * @return string
     */
    public function filter_post_link( $permalink, $post ) {
        // Only modify permalinks for published posts in the News category
        if ( $post->post_status !== 'publish' || $post->post_type !== 'post' ) {
            return $permalink;
        }

        // Check if post is in News category
        if ( ! has_category( 'news', $post ) ) {
            return $permalink;
        }

        // Get the source permalink
        $source_permalink = get_post_meta( $post->ID, '_source_permalink', true );

        if ( ! empty( $source_permalink ) ) {
            return esc_url( $source_permalink );
        }

        return $permalink;
    }

    /**
     * Add target="_blank" and rel attributes to News category post links
     *
     * @param string $link The post's link HTML
     * @param WP_Post $post The post object
     * @return string
     */
    public function modify_post_link_attributes( $link, $post ) {
        // Only modify links for News category posts with source permalinks
        if ( $post->post_type !== 'post' || ! has_category( 'news', $post ) ) {
            return $link;
        }

        $source_permalink = get_post_meta( $post->ID, '_source_permalink', true );

        if ( empty( $source_permalink ) ) {
            return $link;
        }

        // Add target="_blank" and security attributes if not already present
        if ( strpos( $link, 'target=' ) === false ) {
            $link = str_replace( '<a ', '<a target="_blank" rel="noopener noreferrer" ', $link );
        }

        return $link;
    }

    /**
     * Add JavaScript to handle external links in News category
     * This ensures links open in new tabs even when generated by theme
     */
    public function add_external_link_script() {
        ?>
        <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Find all links within News category articles
            var articles = document.querySelectorAll('article.category-news .entry-title a, article.category-news .post-thumbnail a');

            articles.forEach(function(link) {
                // Add target="_blank" for external links
                var hostname = new URL(link.href).hostname;
                if (hostname !== window.location.hostname) {
                    link.setAttribute('target', '_blank');
                    link.setAttribute('rel', 'noopener noreferrer');
                }
            });
        });
        </script>
        <?php
    }
}
